version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    links:
    - redis
    - db
    environment:
      DEBUG: 1
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: ''
  redis:
    image: redis
  db:
    image: postgres:12
    volumes:
    - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
    - "8080:8080"
    links:
    - db
volumes:
  dbdata: {}
